#配置启动端口
server:
  port: 9090
#配置mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/books?serverTimezone=GMT%2b8
    username: root
    password: root
#mybatis的配置
mybatis:
  mapper-locations: classpath:mapper/*.xml #classpath就是resources文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: D:/Project/WorkProject/web/files/
